# Install useful R packages and dependencies for rareMETALS2
sudo su - -c "R -e \"install.packages('tidyverse', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('readr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('dplyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('stringi', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('tidyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('dummies', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('seqminer', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('mvtnorm', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('CompQuadForm', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('getopt', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('data.table', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('curl', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('stringr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"devtools::install_github('gabraham/flashpca/flashpcaR')\""
