FILE <- Sys.getenv("FILE")
library(readr)
library(stringr)
library(dplyr)
library(stringi)
NEWFILENAME <- FILE %>% str_replace("_AD_fields", "") %>% str_replace("_header.tab", "")
AD_depths_sum <- read_delim(str_c("split_processed_depth_files/AD_depths_sum_", FILE), delim="\t", col_types = cols(.default="c"))
AD_depths_sum_numeric <- NULL
AD_depths_sum_numeric <- as.data.frame(matrix(NA, dim(AD_depths_sum)[1],dim(AD_depths_sum)[2]))
names(AD_depths_sum_numeric) <- names(AD_depths_sum)
system.time(for (i in 1:dim(AD_depths_sum)[1]){
    AD_depths_sum_numeric[i,] <- sapply(AD_depths_sum[i,], function(x) eval(parse(text=as.character(x))))
    print(str_c("Completed row ", i, "!"))
})
rm(AD_depths_sum)
gc()
n_samples <- length(names(AD_depths_sum_numeric))
sample_ids <- names(AD_depths_sum_numeric) %>% str_replace(".AD", "")
names(AD_depths_sum_numeric) <- sample_ids
variant_ids <- read_delim(str_c("split_processed_depth_files/variant_ids_", FILE), delim=",", col_types = cols(.default="c"))
variant_ids_name <- "ID"
full_header <- str_c(c(variant_ids_name, sample_ids), collapse=",")
write.table(full_header, "split_processed_depth_files_summed_DP_ALT/HEADER.txt", sep="", quote=FALSE, row.names=FALSE, col.names=FALSE)
AD_depths_sum_with_variantid <- bind_cols(variant_ids, AD_depths_sum_numeric)
rm(AD_depths_sum_numeric)
gc()
write.table(AD_depths_sum_with_variantid, str_c("split_processed_depth_files_summed_DP_ALT/AD_matrix_", NEWFILENAME, ".csv"), sep=",", quote=FALSE, row.names=FALSE, col.names=FALSE)
rm(AD_depths_sum_with_variantid)
gc()